// Simulated in-memory Linux file system for terminal missions

export interface FSNode {
  type: 'file' | 'dir';
  name: string;
  content?: string;
  children?: Record<string, FSNode>;
  permissions?: string; // e.g. 'rwxr-xr-x'
  owner?: string;
  group?: string;
  size?: number;
  modified?: string;
}

function dir(name: string, children: Record<string, FSNode>, perms = 'rwxr-xr-x'): FSNode {
  return { type: 'dir', name, children, permissions: perms, owner: 'user', group: 'user', modified: 'Feb 21 12:00' };
}

function file(name: string, content = '', perms = 'rw-r--r--', size?: number): FSNode {
  return { type: 'file', name, content, permissions: perms, owner: 'user', group: 'user', size: size || content.length || 0, modified: 'Feb 21 12:00' };
}

export function createDefaultFS(): FSNode {
  return dir('/', {
    'home': dir('home', {
      'user': dir('user', {
        'Desktop': dir('Desktop', {
          'notes.txt': file('notes.txt', 'Remember to learn terminal commands!\nThis is going to be awesome.'),
          'todo.md': file('todo.md', '# TODO\n- Learn terminal\n- Practice commands\n- Build cool stuff'),
          'project': dir('project', {
            'index.html': file('index.html', '<!DOCTYPE html>\n<html>\n<head><title>My Site</title></head>\n<body><h1>Hello World!</h1></body>\n</html>'),
            'style.css': file('style.css', 'body { color: white; background: #0a0e1a; }'),
            'app.js': file('app.js', 'console.log("Hello from NetQuest!");'),
          }),
        }),
        'Documents': dir('Documents', {
          'report.txt': file('report.txt', 'Quarterly Report\n\nServer uptime: 99.9%\nTotal users: 1,234\nBandwidth: 500GB'),
          'passwords.txt': file('passwords.txt', 'admin:supersecret123\nroot:hunter2\nuser:password123', 'rw-------'),
          'readme.md': file('readme.md', '# Welcome\nThis is your documents folder.'),
        }),
        'Downloads': dir('Downloads', {
          'package.tar.gz': file('package.tar.gz', '[binary data]', 'rw-r--r--', 2048),
          'image.png': file('image.png', '[binary data]', 'rw-r--r--', 15360),
          'script.sh': file('script.sh', '#!/bin/bash\necho "Hello from script!"\ndate\nwhoami', 'rw-r--r--'),
        }),
        'Music': dir('Music', {}),
        'Pictures': dir('Pictures', {
          'vacation.jpg': file('vacation.jpg', '[binary data]', 'rw-r--r--', 3145728),
        }),
        '.bashrc': file('.bashrc', '# ~/.bashrc\nexport PS1="\\u@\\h:\\w$ "\nexport PATH="$HOME/bin:$PATH"\nalias ll="ls -la"\nalias gs="git status"'),
        '.bash_history': file('.bash_history', 'ls\ncd Desktop\npwd\ncat notes.txt\nclear'),
      }),
    }),
    'etc': dir('etc', {
      'hostname': file('hostname', 'netquest-vm'),
      'hosts': file('hosts', '127.0.0.1\tlocalhost\n127.0.1.1\tnetquest-vm\n::1\tlocalhost'),
      'passwd': file('passwd', 'root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nbin:x:2:2:bin:/bin:/usr/sbin/nologin\nsys:x:3:3:sys:/dev:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\nuser:x:1000:1000:User:/home/user:/bin/bash\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin'),
      'shadow': file('shadow', 'root:$6$xyz:19000:0:99999:7:::\nuser:$6$abc:19000:0:99999:7:::', 'rw-------'),
      'group': file('group', 'root:x:0:\ndaemon:x:1:\nbin:x:2:\nsys:x:3:\nadm:x:4:user\nwww-data:x:33:\nsudo:x:27:user\nusers:x:100:user\nuser:x:1000:'),
      'sudoers': file('sudoers', '# /etc/sudoers\n#\n# This file MUST be edited with visudo\n#\nDefaults\tenv_reset\nDefaults\tmail_badpass\nDefaults\tsecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"\n\n# User privilege specification\nroot\tALL=(ALL:ALL) ALL\n\n# Members of the sudo group\n%sudo\tALL=(ALL:ALL) ALL', 'r--r-----'),
      'fstab': file('fstab', '# /etc/fstab: static file system information.\n#\n# <file system>  <mount point>  <type>  <options>       <dump>  <pass>\nUUID=a1b2c3d4    /              ext4    errors=remount-ro 0       1\nUUID=e5f6g7h8    /boot          ext4    defaults        0       2\n/dev/sda2        none           swap    sw              0       0\ntmpfs            /tmp           tmpfs   defaults        0       0'),
      'resolv.conf': file('resolv.conf', '# Generated by NetworkManager\nnameserver 8.8.8.8\nnameserver 8.8.4.4\nsearch localdomain'),
      'os-release': file('os-release', 'NAME="Ubuntu"\nVERSION="22.04.3 LTS (Jammy Jellyfish)"\nID=ubuntu\nID_LIKE=debian\nPRETTY_NAME="Ubuntu 22.04.3 LTS"\nVERSION_ID="22.04"\nHOME_URL="https://www.ubuntu.com/"\nSUPPORT_URL="https://help.ubuntu.com/"'),
      'nginx': dir('nginx', {
        'nginx.conf': file('nginx.conf', 'server {\n  listen 80;\n  root /var/www/html;\n  index index.html;\n}'),
      }),
      'ssh': dir('ssh', {
        'sshd_config': file('sshd_config', 'Port 22\nPermitRootLogin no\nPasswordAuthentication yes'),
      }),
      'crontab': file('crontab', '# /etc/crontab: system-wide crontab\nSHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n\n# m h dom mon dow user  command\n17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly\n25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )\n47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )'),
      'systemd': dir('systemd', {
        'system': dir('system', {
          'nginx.service': file('nginx.service', '[Unit]\nDescription=A high performance web server\nAfter=network.target\n\n[Service]\nType=forking\nExecStart=/usr/sbin/nginx\nExecReload=/bin/kill -s HUP $MAINPID\nExecStop=/bin/kill -s QUIT $MAINPID\n\n[Install]\nWantedBy=multi-user.target'),
          'sshd.service': file('sshd.service', '[Unit]\nDescription=OpenBSD Secure Shell server\nAfter=network.target\n\n[Service]\nExecStart=/usr/sbin/sshd -D\nExecReload=/bin/kill -HUP $MAINPID\n\n[Install]\nWantedBy=multi-user.target'),
        }),
      }),
    }),
    'var': dir('var', {
      'log': dir('log', {
        'syslog': file('syslog', 'Feb 21 12:00:01 netquest systemd[1]: Started Daily apt activities.\nFeb 21 12:00:02 netquest CRON[1234]: (root) CMD (test -x /usr/sbin/anacron)\nFeb 21 12:01:00 netquest nginx[5678]: 192.168.1.1 - GET /index.html 200\nFeb 21 12:01:01 netquest sshd[9012]: Accepted password for user from 10.0.0.5\nFeb 21 12:02:00 netquest nginx[5678]: 10.0.0.3 - GET /api/data 404\nFeb 21 12:05:00 netquest kernel: [42069.123] Out of memory: Killed process 1337 (crypto-miner)\nFeb 21 12:05:01 netquest systemd[1]: mysql.service: Main process exited, code=exited, status=1/FAILURE\nFeb 21 12:05:02 netquest systemd[1]: mysql.service: Failed with result \'exit-code\'.\nFeb 21 12:06:00 netquest nginx[5678]: 192.168.1.5 - GET /admin 403'),
        'auth.log': file('auth.log', 'Feb 21 11:00:00 sshd[1001]: Failed password for root from 203.0.113.50\nFeb 21 11:00:05 sshd[1002]: Failed password for root from 203.0.113.50\nFeb 21 11:00:10 sshd[1003]: Failed password for admin from 203.0.113.50\nFeb 21 11:01:00 sshd[1004]: Failed password for root from 203.0.113.50\nFeb 21 11:01:05 sshd[1005]: Failed password for root from 203.0.113.50\nFeb 21 12:01:01 sshd[9012]: Accepted password for user from 10.0.0.5\nFeb 21 12:30:00 sudo: user : TTY=pts/0 ; PWD=/home/user ; USER=root ; COMMAND=/bin/apt update'),
        'kern.log': file('kern.log', 'Feb 21 10:00:00 netquest kernel: [    0.000000] Linux version 5.15.0-91-generic (buildd@lcy02-amd64-051)\nFeb 21 10:00:00 netquest kernel: [    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.15.0-91-generic root=UUID=a1b2c3d4\nFeb 21 10:00:01 netquest kernel: [    0.500000] Memory: 2048MB available\nFeb 21 10:00:02 netquest kernel: [    1.200000] CPU: Intel Core i5-9600K @ 3.70GHz\nFeb 21 12:05:00 netquest kernel: [42069.123] Out of memory: Killed process 1337 (crypto-miner)'),
        'dpkg.log': file('dpkg.log', '2026-02-20 10:00:00 install nginx 1.18.0-6ubuntu14.4\n2026-02-20 10:00:01 status installed nginx 1.18.0-6ubuntu14.4\n2026-02-21 09:00:00 upgrade openssh-server 1:8.9p1-3ubuntu0.4 1:8.9p1-3ubuntu0.5'),
        'nginx': dir('nginx', {
          'access.log': file('access.log', '192.168.1.1 - - [21/Feb/2026:12:01:00] "GET /index.html HTTP/1.1" 200 1234\n10.0.0.3 - - [21/Feb/2026:12:01:01] "GET /api/data HTTP/1.1" 404 0'),
          'error.log': file('error.log', '2026/02/21 12:02:00 [error] 5678#5678: *1 open() "/var/www/html/api/data" failed (2: No such file or directory)'),
        }),
      }),
      'www': dir('www', {
        'html': dir('html', {
          'index.html': file('index.html', '<!DOCTYPE html>\n<html><body><h1>Welcome to nginx!</h1></body></html>'),
        }),
      }),
    }),
    'tmp': dir('tmp', {
      'session_abc123': file('session_abc123', 'temp data'),
    }),
    'usr': dir('usr', {
      'bin': dir('bin', {
        'python3': file('python3', '[binary]', 'rwxr-xr-x', 4096),
        'node': file('node', '[binary]', 'rwxr-xr-x', 8192),
        'git': file('git', '[binary]', 'rwxr-xr-x', 2048),
      }),
      'local': dir('local', {
        'bin': dir('bin', {}),
      }),
    }),
    'proc': dir('proc', {
      'cpuinfo': file('cpuinfo', 'processor\t: 0\nvendor_id\t: GenuineIntel\nmodel name\t: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz\ncpu MHz\t\t: 3700.000\ncache size\t: 9216 KB\ncpu cores\t: 6'),
      'meminfo': file('meminfo', 'MemTotal:        2097152 kB\nMemFree:          524288 kB\nMemAvailable:     1048576 kB\nBuffers:           65536 kB\nCached:           458752 kB\nSwapTotal:       1048576 kB\nSwapFree:        1000000 kB'),
      'uptime': file('uptime', '432000.00 1728000.00'),
      'version': file('version', 'Linux version 5.15.0-91-generic (buildd@lcy02-amd64-051) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0)'),
    }),
    'dev': dir('dev', {
      'sda': file('sda', '[block device]', 'brw-rw----'),
      'sda1': file('sda1', '[block device]', 'brw-rw----'),
      'sda2': file('sda2', '[block device]', 'brw-rw----'),
      'null': file('null', '', 'crw-rw-rw-'),
      'zero': file('zero', '', 'crw-rw-rw-'),
      'random': file('random', '', 'crw-rw-rw-'),
      'tty': file('tty', '', 'crw-rw-rw-'),
    }),
    'bin': dir('bin', {
      'bash': file('bash', '[binary]', 'rwxr-xr-x', 1024),
      'ls': file('ls', '[binary]', 'rwxr-xr-x', 512),
      'cat': file('cat', '[binary]', 'rwxr-xr-x', 512),
    }),
    'root': dir('root', {}, 'rwx------'),
  });
}

export function resolvePath(fs: FSNode, cwd: string, target: string): string {
  // Handle ~ as /home/user
  target = target.replace(/^~/, '/home/user');
  
  let parts: string[];
  if (target.startsWith('/')) {
    parts = target.split('/').filter(Boolean);
  } else {
    parts = [...cwd.split('/').filter(Boolean), ...target.split('/').filter(Boolean)];
  }

  // Resolve . and ..
  const resolved: string[] = [];
  for (const p of parts) {
    if (p === '.') continue;
    if (p === '..') { resolved.pop(); continue; }
    resolved.push(p);
  }
  return '/' + resolved.join('/');
}

export function getNode(fs: FSNode, path: string): FSNode | null {
  if (path === '/') return fs;
  const parts = path.split('/').filter(Boolean);
  let current = fs;
  for (const part of parts) {
    if (current.type !== 'dir' || !current.children?.[part]) return null;
    current = current.children[part];
  }
  return current;
}

export function getParentAndName(fs: FSNode, path: string): { parent: FSNode | null; name: string } {
  const parts = path.split('/').filter(Boolean);
  if (parts.length === 0) return { parent: null, name: '' };
  const name = parts.pop()!;
  const parentPath = '/' + parts.join('/');
  return { parent: getNode(fs, parentPath), name };
}

export function formatPermissions(node: FSNode): string {
  const prefix = node.type === 'dir' ? 'd' : '-';
  return prefix + (node.permissions || 'rw-r--r--');
}

export function formatLsLine(node: FSNode): string {
  const perms = formatPermissions(node);
  const links = node.type === 'dir' ? '2' : '1';
  const owner = node.owner || 'user';
  const group = node.group || 'user';
  const size = String(node.size || (node.content?.length || 0)).padStart(6);
  const date = node.modified || 'Feb 21 12:00';
  return `${perms} ${links} ${owner} ${group} ${size} ${date} ${node.name}`;
}
